---
:ticker:
  :url: http://www.example.com/news
:db:
  :adapter: sqlite3
  :database: db/jabber_ticker_dev.sqlite3
:bot:
  :jabber_id: ticker@jabber.example.com
  :name: Example Ticker Bot
  :password: foobar
  :master: tickermaster@example.com
  # master password is not required for the bot, but we use it in the command line client bin/ticker
  :master_password: WOLRH7iLba82pTwc6Q7k
  :is_public: true
